### ISSUE TITLE
cannot reproduce VOC 15-1

### ISSUE THREAD

**Issue by Ze-Yang** [HieuPhan33/REMINDER#3]
I directly ran with the script reminder_15-1.sh, but obtained lower results on old classes. I can reproduce 15-5 and 19-1 though. Looking forward to your advice.

|            | 0-15 | 16-20 |  all |
|-----|:------:|:-------:|:------:|
| Reported   | 68.30 | 27.23 | 58.52 |
| Reproduced | 66.37 | 27.03 | 57.00 |

**Comment by HieuPhan33** [comment]
Hi ZeYang, could you please confirm if you use a batch size of 16?
Secondly, I also find that removing the threshold (considering all old classes when doing KD) can improve the results for VOC. You can try commenting out this line of code: https://github.com/HieuPhan33/REMINDER/blob/9796af7c497cf24843e5d97653b08af1b1bd6bd9/utils/loss.py#L357.

Since Pascal VOC has a small set of classes (compared with ADE20k), we can use all old classes during KD.

FYI, here is my result:
[2022-05-25_voc_15-5s_REMINDER.csv](https://github.com/HieuPhan33/REMINDER/files/9334459/2022-05-25_voc_15-5s_REMINDER.csv)

**Comment by Ze-Yang** [comment]
Hi @HieuPhan33, I strictly follow your script to use a batch size of 16.

As for the threshold, `--delta_csw` is by default set to 0 in the args. Therefore, there will be no effect of threshold actually. You may try re-run this experiment to see whether it is reproducible.

**Comment by HieuPhan33** [comment]
Hi,
Could you try running the code on branch master? 

I just re-run experiments on this branch and get a mIoU of 58.27%.

To save your time, I uploaded step0-checkpoint [here](https://drive.google.com/file/d/178O5rdFPnQAkRTPaJroBSVi5y0eHLKqR/view?usp=sharing).

We have many code versions. Looks like the version on the main branch does not work well in all settings.

Our lab rented a GPU server from AWS. I often stop the instances to save costs.
I migrate the code frequently and have multiple versions.
Due to a lack of experience in managing code, I have difficulty finalizing the best code version.

The strange thing is that master, and the main branch are almost identical. I am trying to synthesize all code bases now. And keep you updated about all settings including ADE20k.

Sorry for the inconvenience.
